{% set name = "COMPAS" %}
{% set version = "2.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 44b5000a46ddd24fb5fb50cdd3e87e518cec23f6032efbb8dabbde2acea18ff6

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - compas_rpc=compas.rpc.__main__:main

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - jsonschema
    - networkx >=3.0
    - numpy >=1.15.4
    - scipy >=1.1
    - watchdog

test:
  imports:
    - compas
    - compas_blender
    - compas_ghpython
    - compas_rhino
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://compas.dev
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: The COMPAS framework
  description: |
    COMPAS is an open-source, Python-based computational framework
    for collaboration and research in architecture, engineering and
    digital fabrication. It is developed by the Block Research
    Group (https://block.arch.ethz.ch) of ETH Zurich (http://www.ethz.ch),
    with the support of the National Centre for Competence in
    Research on "Digital Fabrication" (http://www.dfab.ch).
  doc_url: https://compas.dev
  dev_url: https://github.com/compas-dev/compas

extra:
  recipe-maintainers:
    - tomvanmele
    - gonzalocasas
