{% set name = "compas" %}
{% set version = "2.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b49f90999f3eaed9ec04c1fb07fe9b768a9268395a42613c72eccabae0d88d1d

build:
  noarch: python
  number: 0
  script:
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - compas_rpc=compas.rpc.__main__:main

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - jsonschema
    - networkx >=3.0
    - numpy >=1.15.4, <2.0
    - scipy >=1.1
    - watchdog

test:
  imports:
    - compas
    - compas_blender
    - compas_ghpython
    - compas_rhino
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://compas.dev
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: The COMPAS framework
  description: |
    COMPAS is an open-source, Python-based computational framework
    for collaboration and research in architecture, engineering and
    digital fabrication. It is developed by the Block Research
    Group (https://block.arch.ethz.ch) of ETH Zurich (http://www.ethz.ch),
    with the support of the National Centre for Competence in
    Research on "Digital Fabrication" (http://www.dfab.ch).
  doc_url: https://compas.dev
  dev_url: https://github.com/compas-dev/compas

extra:
  recipe-maintainers:
    - tomvanmele
    - gonzalocasas
