{% set name = "COMPAS" %}
{% set version = "1.17.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b3a7e05e177409161a698bf98680769f41a62b56d67d312de1f6c63341f8d75f

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - compas_rpc=compas.rpc.__main__:main

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools
  run:
    - cython
    - python
    - imageio >=2.7
    - jsonschema >=4.17,<4.18
    - matplotlib-base >=2.2,<3.1  # [win and py<=37]
    - matplotlib-base >=3.1       # [win and py>=38]
    - matplotlib-base >=2.2       # [not win]
    - networkx
    - numpy
    - pillow
    - pycollada
    - schema
    - scipy >=1.1
    - sympy
    - typing_extensions
    - watchdog

test:
  imports:
    - compas
    - compas_blender
    - compas_ghpython
    - compas_rhino
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://compas.dev
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: The COMPAS framework
  description: |
    COMPAS is an open-source, Python-based computational framework
    for collaboration and research in architecture, engineering and
    digital fabrication. It is developed by the Block Research
    Group (https://block.arch.ethz.ch) of ETH Zurich (http://www.ethz.ch),
    with the support of the National Centre for Competence in
    Research on "Digital Fabrication" (http://www.dfab.ch).
  doc_url: https://compas.dev
  dev_url: https://github.com/compas-dev/compas

extra:
  recipe-maintainers:
    - tomvanmele
    - gonzalocasas
