{% set name = "COMPAS" %}
{% set version = "1.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6f38d883c2bf19551d43f95176685c882299ca1f22a32dd1c9b2e1e82920cf4d

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - compas_rpc=compas.rpc.__main__:main

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - cython
    - ezdxf
    - python
    - imageio >=2.7
    - jsonschema
    - laspy
    - matplotlib-base >=2.2,<3.1  # [win and py<=37]
    - matplotlib-base >=3.1       # [win and py>=38]
    - matplotlib-base >=2.2       # [not win]
    - networkx
    - numba
    - numpy
    - pillow
    - pycollada
    - python-planarity
    - schema
    - scipy >=1.1
    - sympy
    - typing_extensions
    - watchdog

test:
  imports:
    - compas
    - compas_blender
    - compas_ghpython
    - compas_rhino
    - compas_plotters
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://compas.dev
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: The COMPAS framework
  description: |
    COMPAS is an open-source, Python-based computational framework
    for collaboration and research in architecture, engineering and
    digital fabrication. It is developed by the Block Research
    Group (https://block.arch.ethz.ch) of ETH Zurich (http://www.ethz.ch),
    with the support of the National Centre for Competence in
    Research on "Digital Fabrication" (http://www.dfab.ch).
  doc_url: https://compas.dev
  dev_url: https://github.com/compas-dev/compas

extra:
  recipe-maintainers:
    - brgcode
    - gonzalocasas
